---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  CloudFormation template for provisioning MYSQL RDS for LANSA Database Regression Test.

Parameters:
  LANSAVERSION:
    Type: String
    Description: LANSA Version that needs to be tested
  SECURITYGROUPID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DB_REGRESSION_TESTING_RDS_SG_ID
    Description: Security Group to be attached to the RDS (Default is in the Parameter Store).
  SNAPSHOTARN:
    Type: String
    Description: MYSQL SNAPSHOT ARN

Resources:

  MYSQLRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier:  !Join [ "", [ "mysql", !Ref LANSAVERSION ] ]
      DBSnapshotIdentifier: !Ref SNAPSHOTARN
      DBInstanceClass: db.t3.large
      Engine: mysql
      VPCSecurityGroups:
        - !Ref SECURITYGROUPID
      EnablePerformanceInsights: true
      CopyTagsToSnapshot: true