---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  CloudFormation template for provisioning of Oracle RDS for LANSA Database Regression Test.

Parameters:
  LANSAVERSION:
    Type: String
    Description: LANSA Version that needs to be tested
  SECURITYGROUPID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DB_REGRESSION_TESTING_RDS_SG_ID
    Description: Security Group to be attached to the RDS (Default is in the Parameter Store).
  SNAPSHOTARN:
    Type: String
    Description: ORACLE SNAPSHOT ARN


Resources:

  ORACLERDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join [ "", [ "ora", !Ref LANSAVERSION ] ]
      DBSnapshotIdentifier: !Ref SNAPSHOTARN
      DBInstanceClass: db.m5.xlarge
      Engine: oracle-se2-cdb
      VPCSecurityGroups:
        - !Ref SECURITYGROUPID
      EnablePerformanceInsights: true
      CopyTagsToSnapshot: true